dist: trusty
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - npm install -g "npm@$(jq -r '.engines.npm' package.json)"
install:
  - npm install
script:
  - npm test
after_success:
  - npm run test/coveralls
branches:
  only:
    - master
